# Generated by Django 4.0.6 on 2023-07-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createusermodel',
            options={'verbose_name': 'Student Submission'},
        ),
    ]
