# Generated by Django 4.0.6 on 2023-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0003_remove_createusermodel_student_checkbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Uploaded File',
            },
        ),
    ]
