# Generated by Django 4.0.6 on 2023-07-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0006_alter_testfilemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfilemodel',
            name='file',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
    ]
