# Generated by Django 4.0.6 on 2023-07-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0009_alter_createusermodel_pdf_file1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='pdf_file1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='pdf_file2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='pdf_file3',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='pdf_file4',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='pdf_file5',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='pdf_id',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
