# Generated by Django 4.0.6 on 2023-07-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0010_alter_createusermodel_pdf_file1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createusermodel',
            name='pdf_id',
        ),
    ]
