# Generated by Django 4.0.6 on 2023-07-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0012_remove_testfilemodel_file_testfilemodel_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='pdf_file1',
            field=models.FileField(default='Choose file', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='firstname',
            field=models.CharField(default='firstname', max_length=100),
        ),
    ]
