# Generated by Django 4.0.6 on 2023-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0014_alter_testfilemodel_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='birthday',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='category1',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='city',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='country',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='email',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='grade_level',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='parent_email',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='parent_firstname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='parent_lastname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='parent_phone_number',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='phone_number',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='school_address',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='school_name',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='title1',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='word_count1',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='zipcode',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='category1',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='category2',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='category3',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='category4',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='category5',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='city',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='country',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='email',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='firstname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='grade_level',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='lastname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='parent_email',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='parent_firstname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='parent_lastname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='parent_phone_number',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='phone_number',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='school_address',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='school_name',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='title1',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='title2',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='title3',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='title4',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='title5',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='word_count1',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='word_count2',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='word_count3',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='word_count4',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='word_count5',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='zipcode',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='pdf_file1',
            field=models.FileField(default='___', upload_to=''),
        ),
    ]
