# Generated by Django 4.0.6 on 2023-07-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0015_testfilemodel_birthday_testfilemodel_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='category2',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='pdf_file2',
            field=models.FileField(default='___', upload_to=''),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='title2',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='word_count2',
            field=models.CharField(default='___', max_length=100),
        ),
    ]
