# Generated by Django 4.0.6 on 2023-07-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0016_testfilemodel_category2_testfilemodel_pdf_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='category3',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='category4',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='category5',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='pdf_file3',
            field=models.FileField(default='___', upload_to=''),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='pdf_file4',
            field=models.FileField(default='___', upload_to=''),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='pdf_file5',
            field=models.FileField(default='___', upload_to=''),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='title3',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='title4',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='title5',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='word_count3',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='word_count4',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='word_count5',
            field=models.CharField(default='___', max_length=100),
        ),
    ]
