# Generated by Django 4.0.6 on 2023-07-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0017_testfilemodel_category3_testfilemodel_category4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUserModel',
        ),
    ]
