# Generated by Django 4.0.6 on 2023-07-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0018_delete_createusermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfilemodel',
            options={'verbose_name': 'Student Submission'},
        ),
    ]
