# Generated by Django 4.2.5 on 2023-11-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0019_alter_testfilemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graded', models.BooleanField()),
                ('review', models.TextField(max_length=300)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
