# Generated by Django 4.2.5 on 2023-11-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0020_judgemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgemodel',
            name='rating',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='judgemodel',
            name='review',
            field=models.CharField(max_length=300),
        ),
    ]
