# Generated by Django 4.2.5 on 2023-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0021_alter_judgemodel_rating_alter_judgemodel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgemodel',
            name='submission',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
