# Generated by Django 4.2.5 on 2023-11-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0022_judgemodel_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgemodel',
            name='graded',
        ),
        migrations.AddField(
            model_name='judgemodel',
            name='graded_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
