# Generated by Django 4.2.5 on 2023-11-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0023_remove_judgemodel_graded_judgemodel_graded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgemodel',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
