# Generated by Django 4.2.7 on 2023-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0024_alter_judgemodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgemodel',
            name='sub_number',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
