# Generated by Django 4.2.7 on 2023-12-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0025_judgemodel_sub_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graded_by', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=5)),
                ('submission', models.CharField(max_length=5)),
                ('sub_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='JudgeModel',
            new_name='JudgeModel1',
        ),
    ]
