# Generated by Django 3.2.16 on 2024-03-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0027_judgemodel3'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='all_judges_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='judge_model1',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_file_model', to='website_data.judgemodel1'),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='judge_model2',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_file_model', to='website_data.judgemodel2'),
        ),
        migrations.AddField(
            model_name='testfilemodel',
            name='judge_model3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_file_model', to='website_data.judgemodel3'),
        ),
    ]
