# Generated by Django 3.2.16 on 2024-03-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0028_auto_20240312_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='is_email_notified',
            field=models.BooleanField(default=False),
        ),
    ]
