# Generated by Django 3.2.16 on 2024-03-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0029_testfilemodel_is_email_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgemodel1',
            name='review',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel1',
            name='sub_number',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel1',
            name='submission',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel2',
            name='review',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel2',
            name='sub_number',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel2',
            name='submission',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel3',
            name='review',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel3',
            name='sub_number',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='judgemodel3',
            name='submission',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
