# Generated by Django 3.2.16 on 2024-03-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0030_auto_20240312_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfilemodel',
            name='birthday',
            field=models.DateField(blank=True, default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='category1',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='category2',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='category3',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='category4',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='category5',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='city',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='country',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='email',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='firstname',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='grade_level',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='lastname',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='parent_email',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='parent_firstname',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='parent_lastname',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='parent_phone_number',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='pdf_file1',
            field=models.FileField(blank=True, default='___', upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='pdf_file2',
            field=models.FileField(blank=True, default='___', upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='pdf_file3',
            field=models.FileField(blank=True, default='___', upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='pdf_file4',
            field=models.FileField(blank=True, default='___', upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='pdf_file5',
            field=models.FileField(blank=True, default='___', upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='phone_number',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='school_address',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='school_name',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='title1',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='title2',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='title3',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='title4',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='title5',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='word_count1',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='word_count2',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='word_count3',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='word_count4',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='word_count5',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='zipcode',
            field=models.CharField(blank=True, default='___', max_length=100),
        ),
    ]
