# Generated by Django 3.2.16 on 2024-03-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0031_auto_20240312_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfilemodel',
            name='judge_model1',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_file_model', to='website_data.judgemodel1'),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='judge_model2',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_file_model', to='website_data.judgemodel2'),
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='judge_model3',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_file_model', to='website_data.judgemodel3'),
        ),
    ]
