# Generated by Django 3.2.16 on 2024-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0032_auto_20240313_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
