# Generated by Django 3.2.16 on 2024-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0033_testfilemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilemodel',
            name='award',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('honor', 'Honor'), ('no_award', 'No Award')], default='no_award', help_text='Select the award category', max_length=10),
        ),
    ]
