# Generated by Django 3.2.16 on 2024-03-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0034_testfilemodel_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique name of the setting.', max_length=255, unique=True)),
                ('value', models.CharField(help_text='Value of the setting.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the setting.')),
            ],
        ),
    ]
