# Generated by Django 3.2.16 on 2024-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_data', '0035_generalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='value',
            field=models.BooleanField(default=True, help_text='Value of the setting.'),
        ),
    ]
